debug = False
apex = False
print_freq = 100
num_workers = 4
model_name = "tf_efficientnet_b4_ns"
size = 512
scheduler = "CosineAnnealingWarmRestarts"  # ['ReduceLROnPlateau', 'CosineAnnealingLR', 'CosineAnnealingWarmRestarts']
criterion = (
    "BiTemperedLoss"
)  # ['CrossEntropyLoss', LabelSmoothing', 'FocalLoss' 'FocalCosineLoss', 'SymmetricCrossEntropyLoss', 'BiTemperedLoss', 'TaylorCrossEntropyLoss']
epochs = 10
# factor=0.2 # ReduceLROnPlateau
# patience=4 # ReduceLROnPlateau
# eps=1e-6 # ReduceLROnPlateau
# T_max=10 # CosineAnnealingLR
T_0 = 10  # CosineAnnealingWarmRestarts
lr = 1e-4
min_lr = 1e-6
batch_size = 12
weight_decay = 1e-6
gradient_accumulation_steps = 1
max_grad_norm = 1000
seed = 42
target_size = 5
target_col = "label"
n_fold = 5
trn_fold = [0]  # Change Values according to the fold which you are training.
train = True
inference = False
smoothing = 0.05
t1 = 0.3  # bi-tempered-loss https://www.kaggle.com/c/cassava-leaf-disease-classification/discussion/202017
t2 = 1.0  # bi-tempered-loss https://www.kaggle.com/c/cassava-leaf-disease-classification/discussion/202017
